### ISSUE TITLE
Feature request: keyboard config / person script

### ISSUE THREAD

**Issue by isidore** [GreatWebGuy/MobTime#10]
It would be great to be able to configure the keyboard per driver.

More generically, it would be nice to execute a small script per driver on start.

1.Jason
2. Ken

On jason start it would execute mobtime.jason.start.py (or something)

**Comment by jlcrow** [comment]
Nice idea, not sure how to do this from JavaFX or how to do it in a cross platform manner. No plans to implement, feel free to submit a PR if you like.

**Comment by schmonz** [comment]
> It would be great to be able to configure the keyboard per driver.

Was just about to file an issue wishing for this. @isidore, have you scripted keyboard-layout switching (any platform)?
