### ISSUE TITLE
pause button is drak grey on windows machine

### ISSUE THREAD

**Issue by isidore** [GreatWebGuy/MobTime#13]
<img width="543" alt="Screen Shot 2020-07-07 at 10 23 48 AM" src="https://user-images.githubusercontent.com/10874/86819045-00126e00-c03c-11ea-8892-c57a5e8faab0.png">

**Comment by claremacrae** [comment]
And on Mac too:

![image](https://user-images.githubusercontent.com/4840096/86835833-970b1480-c094-11ea-98e9-af7179a61250.png)

**Comment by jlcrow** [comment]
@isidore @claremacrae Thanks, pushing a fix soon.

**Comment by jlcrow** [comment]
Fixed in v1.7.2

**Comment by claremacrae** [comment]
Thank you @jlcrow! I can confirm that this works - tested on Windows.

(I also learned that there is also a Play button, which I'd never seen before...)
