### ISSUE TITLE
Consider making versions be whole numbers

### ISSUE THREAD

**Issue by JayBazuzi** [GreatWebGuy/MobTime#23]
I'm currently using 1.7.4 and if the next version is 1.7.5 or 1.8.0 or 2.0.0, I don't really care. I'll upgrade. 

If you just call it v2 then v3 then v4 I don't have to notice those details.

Google Chrome does this. You can, too.

**Comment by jlcrow** [comment]
This is a semver format to indicate how significant the change was, it's a common development practice. Glad you're enjoying the tool.
