### ISSUE TITLE
Is it possible to prevent multiple instances of MobTime running

### ISSUE THREAD

**Issue by claremacrae** [GreatWebGuy/MobTime#25]
@isidore and I have been doing a lot of mobbing on Windows with MobTime - it's great, thanks!

Pretty much every session we somehow accidentally end up with a second instance of MobTime, and it gets really confusing really quickly.

Is there a way to run it and prevent a second instance, or would it be possible for a second launch of the program to bring the earlier one to the front and then quit - to force it only allow a single instance, by default.

**Comment by jlcrow** [comment]
@claremacrae Sure, I'll give it a look and see what I can do about that, thanks for the feedback.
