### ISSUE TITLE
Version v1.7.5 does not open a window

### ISSUE THREAD

**Issue by claremacrae** [GreatWebGuy/MobTime#27]
Thank you for fixing #25, and allowing only a single instance.

Oddly, I have not been able to get v1.7.5 to launch the GUI

I've seen this on two different VMs.

I just ran a fresh install of v1.7.5 with procmon running - and what I see is that MobTime.exe launched and immediately exited.

Sorry to be the bearer of bad news!

**Comment by jlcrow** [comment]
Could you let me know what Operating system you're running on?  The behavior sounds like the application is unable to reserve the port it's attempting to open to determine if another version is running. Also as a test could you try running as root just as a test?

**Comment by claremacrae** [comment]
Ah yes, sorry, if you don't know Procmon that was a bit cryptic.

Windows 10 in both cases.

**Comment by jlcrow** [comment]
I guess I should have noticed the .exe extension too :-), I'll have a look and see.
