### ISSUE TITLE
Create chocolate package to install Windows version

### ISSUE THREAD

**Issue by jawn** [GreatWebGuy/MobTime#30]
Create a chocolatey package for MobTime. This provides easy installation and updates.

http://chocolatey.org

**Comment by jawn** [comment]
I am willing to pair/mob on this, ping me if interested. I have no experience in creating such a package, however the [docs are out there](https://docs.chocolatey.org/en-us/create/).

**Comment by jlcrow** [comment]
This is a duplicate of #29
